name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH with PEM key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PEM_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH to EC2 and pull the latest code
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ${{ secrets.EC2_PROJECT_PATH }}
          git pull origin main
          ./gradlew build
          pkill -f 'java -jar' || true
          nohup java -jar build/libs/myapp-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
          EOF
