spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: hApYnEsFX2JvXCW6cYuu6rSN2hLIm9Lv
            scope:
              #              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            #            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-name: Kakao
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: cf7409c8729d7ab5bfdfeceaa639b383
#            client-secret: hApYnEsFX2JvXCW6cYuu6rSN2hLIm9Lv
#            redirect-uri: http://localhost:8080/callback
#
##kakao:
##  client_id: cf7409c8729d7ab5bfdfeceaa639b383
##  redirect_uri: http://localhost:8080/callback