name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - develop  # develop 브랜치에 푸시될 때마다 실행

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # GitHub Actions에서 사용할 환경 (Ubuntu)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # GitHub 리포지토리의 코드를 체크아웃

    - name: Set up JDK 17
      uses: actions/setup-java@v2  # JDK 설정
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Grant execute permission for Gradle
      run: chmod +x ./backend/gradlew

    - name: Build with Gradle
      run: ./backend/gradlew build  # Gradle을 사용하여 프로젝트 빌드

    - name: Transfer JAR file to EC2
      run: |
        echo "${{ secrets.AWS_SSH_KEY }}" > key.pem
        chmod 400 key.pem
        scp -i key.pem -o StrictHostKeyChecking=no ./backend/build/libs/*.jar ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app.jar

    - name: SSH into EC2 and deploy
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
        # 기존 실행 중인 Spring 애플리케이션을 종료
        pkill -f 'java' || true
        # 새로운 애플리케이션을 백그라운드에서 실행
        nohup java -jar /home/${{ secrets.EC2_USER }}/app.jar > /dev/null 2>&1 &
        EOF

    - name: Set environment variables and run on EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
        export TRAVVELCOME_DB_PASSWORD="${{ secrets.TRAVVELCOME_DB_PASSWORD }}"
        export OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
        export OPENAI_MODEL_ID="${{ secrets.OPENAI_MODEL_ID }}"
        export KAKAO_CLIENT_ID="${{ secrets.KAKAO_CLIENT_ID }}"
        export KAKAO_REDIRECT_URI="${{ secrets.KAKAO_REDIRECT_URI }}"
        nohup java -jar /home/${{ secrets.EC2_USER }}/app.jar > /dev/null 2>&1 &
        EOF
